name: Build and Release

on:
  push:
    tags:
      - 'v*'
      - '[0-9]{4}-[0-9]{2}-[0-9]{2}'

jobs:
  build_wheels:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install pip wheel
        run: python -m pip install wheel

      - name: Build wheel
        run: python -m pip wheel . --wheel-dir wheelhouse

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: ${{ github.event.head_commit.message }}
          draft: false
          prerelease: false

      - name: Upload wheels to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: wheelhouse/*.whl
          asset_name: 'ezid_client_tools-${{ github.ref }}-${{ matrix.os }}.whl'
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
